import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Script from "next/script";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mosaico Genética Médica",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <script type="module" intersection-observer="true" src="https://unpkg.com/@splinetool/viewer@1.0.93/build/spline-viewer.js" async ></script>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
