import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Script from "next/script";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mosaico Genética Médica",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        {children}
        <Script type="module" src="https://unpkg.com/@splinetool/viewer@1.0.93/build/spline-viewer.js" strategy="beforeInteractive"></Script>
      </body>
    </html>
  );
}
